name: "lit-autoencoder"
platform: "pytorch_libtorch"
max_batch_size: 2048

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [50]
  }
]

output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [50]
  }
]
